# Skinner, KT., et al, 2026. "Derivation of a doxorubicin mutational signature in cancer". Genome Research
# Contact for questions: Katie Skinner; katie.skinner@emory.edu

# Code for figures presented in Supplemental Figure 9 of manuscript

# load libraries
library(sigProcessor)
library(tidyverse)
library(data.table)

# set working directory
setwd("~/doxorubicin_mutSig/data/")

## Figure S9A-C
# read in table of annotated mutations
# this file was generated by inputting VCFs for each doxorubicin exposed sample into OpenCRAVAT
annotated <- rbind(read.table("/path/to/BT16_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/CHLA-06-ATRT_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/PEDS0005_T1_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/PEDS9001_T1_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/HepG2_doxorubicin_clone1_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/HepG2_doxorubicin_clone2_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/MCF10A_doxorubicin_clone1_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/MCF10A_doxorubicin_clone2_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T)) # data not included due to controlled access

# read in and process SBS VCFs
genome_data <- prepare_sbs96_vcf(c("/path/to/BT16_doxorubicin_SBS_VCF",
                                   "/path/to/CHLA-06-ATRT_doxorubicin_SBS_VCF",
                                   "/path/to/PEDS0005_T1_doxorubicin_SBS_VCF",
                                   "/path/to/PEDS9001_T1_doxorubicin_SBS_VCF",
                                   "/path/to/HepG2_doxorubicin_clone1_SBS_VCF",
                                   "/path/to/HepG2_doxorubicin_clone2_SBS_VCF",
                                   "/path/to/MCF10A_doxorubicin_clone1_SBS_VCF",
                                   "/path/to/MCF10A_doxorubicin_clone2_SBS_VCF")) # data not included due to controlled access

# loop through both lists and confirm that they are in the same order
for (i in 1:length(annotated)) {
  
  cat(paste0("Sample index: ", i, ". "))
  cat(paste0("Annotated sample: ", annotated[[i]]$samples |> unique(), ". "))
  cat(paste0("Genome sample: ", genome_data[[i]]$sample |> unique(), ". "))
  cat("\n")
  
}

# both dfs are in the same order!

# process the dfs
annotated_subset <- list()
for (i in 1:length(annotated)) {
  
  # subset each list for each sample
  a <- annotated[[i]]
  g <- genome_data[[i]]
  
  # narrow down the columns
  a <- a %>% dplyr::select(chrom, pos, ref_base, alt_base, exonno, coding, hugo, so, samples, transcript)
  g <- g %>% select(chrom, pos, sbs6, sample, strand)
  
  # filter to remove non-canonical chromosomes in annotated df
  a <- a %>% filter(chrom %in% paste0("chr", c(1:22, "X", "Y", "M")))
  
  # ensure the chromosome names are in the same format
  a$chrom <- str_replace(a$chrom, pattern = "chrM", replacement = "chrMT")
  
  # in genome data, add a ref and alt base 
  g <- g %>% mutate(ref = substr(g$sbs6, 1, 1),
                    alt = substr(g$sbs6, 3, 3))
  
  # convert everything back to a mix of purines and pyrimidines
  # strand of -1 indicates that the reference base was a purine, thus both ref>alt were converted to their complement
  ref_base <- c()
  alt_base <- c()
  
  for (j in 1:nrow(g)) {
    
    if(g$strand[j] == -1) {
      
      ref_base <- c(ref_base, chartr(old="ATGC", new="TACG", g$ref[j]))
      alt_base <- c(alt_base, chartr(old="ATGC", new="TACG", g$alt[j]))
      
    } else {
      
      ref_base <- c(ref_base, g$ref[j])
      alt_base <- c(alt_base, g$alt[j])
      
    }
  }
  
  # add these to the df
  g$ref_base <- ref_base
  g$alt_base <- alt_base
  
  rm(ref_base, alt_base, j); gc() # clean
  
  # remove INDELs from annotated list
  a <- a %>% filter(!ref_base == "-" & !alt_base == "-") %>%
    filter(nchar(ref_base) == nchar((alt_base)))
  
  # SigProfiler treats dinucleotide substitutions as two single base substitutions
  # find the DBSs
  dbs <- a %>% filter(nchar(ref_base) == 2 & nchar(alt_base) == 2)
  
  # split up each DBS
  dbs_split <- c()
  for (x in 1:nrow(dbs)) {
    
    # define ref bases
    ref1 <- substr(dbs$ref_base[x], 1, 1)
    ref2 <- substr(dbs$ref_base[x], 2, 2)
    
    # define alt bases
    alt1 <- substr(dbs$alt_base[x], 1, 1)
    alt2 <- substr(dbs$alt_base[x], 2, 2)
    
    # build the row
    r1 <- c(dbs$chrom[x], dbs$pos[x], ref1, alt1, dbs$exonno[x], dbs$coding[x], dbs$hugo[x], "DBS", dbs$samples[x], dbs$transcript[x])
    r2 <- c(dbs$chrom[x], dbs$pos[x]+1, ref2, alt2, dbs$exonno[x], dbs$coding[x], dbs$hugo[x], "DBS", dbs$samples[x], dbs$transcript[x])
    
    # append the row to the df
    dbs_split <- rbind(dbs_split, r1, r2)
    
  }
  
  rm(ref1, ref2, alt1, alt2, r1, r2, dbs); gc() # clean
  
  # convert to df
  dbs_split <- dbs_split |> as.data.frame()
  
  # add column names
  colnames(dbs_split) <- colnames(a)
  
  # append to the annotated df
  a <- rbind(a, dbs_split)
  
  # reset rownames
  rownames(a) <- NULL
  
  # create an ID for chrom, pos, ref, and alt to facilitate filtering
  a$ID <- paste0(a$chrom, "_", a$pos, "_", a$ref_base, "/", a$alt_base)
  g$ID <- paste0(g$chrom, "_", g$pos, "_", g$ref_base, "/", g$alt_base)
  
  # find the overlap
  s <- a %>% filter(ID %in% g$ID)
  
  # add to list
  annotated_subset[[i]] <- s
  names(annotated_subset)[i] <- g$sample |> unique()
  
  # clean environment
  rm(a, dbs_split, g, s, x); gc()
  
}

# now that we have our dfs, loop through and determine if any DBS fell in coding regions
annotated_final <- list()
for (i in 1:length(annotated_subset)) {
  
  # subset list
  df <- annotated_subset[[i]]
  
  # locate our DBSs, encoded as "DBS" in the "so" column
  # also check if any of these are coding
  dbs <- df %>% filter(so == "DBS" & coding == "Yes")
  
  # print message
  message(paste0("Number of coding DBSs in ", names(annotated_subset)[i], ": ", nrow(dbs)))
  
  # remove "DBS" label from "so" column
  if (nrow(dbs) == 0) {
    
    df$so <- str_remove(df$so, "DBS")
    
  } else {
    
    df$so <- str_remove(df$so, "DBS")
    
    # also print off the sample and coordinates for the coding DBSs
    cat(paste0("Sample: ", names(annotated_subset)[i], "\n"))
    cat(paste0("Coordinates of coding DBSs:\n"))
    print(dbs)
    
  }
  
  # append the scrubbed df to final list
  annotated_final[[i]] <- df
  names(annotated_final)[i] <- names(annotated_subset)[i]
  
  # clean environment
  rm(dbs, df); gc()
  
}

# according to the output of the above loop, we have 2 coding DBSs in CHLA-06-ATRT_doxorubicin
# does splitting this DBS up still result in a coding change? 
  # yes. go into IGV to validate if both are still missense
  # yes they are.

# update each entry to reflect that
# index of each mutation: 
  # 9179
  # 9180

# fix
annotated_final$`CHLA-06-ATRT_doxorubicin`[9179,8] <- "missense"
annotated_final$`CHLA-06-ATRT_doxorubicin`[9180,8] <- "missense"

# sanity check
annotated_final$`CHLA-06-ATRT_doxorubicin`[9179,]
annotated_final$`CHLA-06-ATRT_doxorubicin`[9180,] # both look good!

# clean environment
rm(annotated, annotated_subset, genome_data, i); gc()

# next, we want to characterise the mutations
# we want to do this on a per signature basis
# so first, concatenate the sample dfs together for each signature
doxo1 <- rbind(annotated_final$BT16_doxorubicin, 
               annotated_final$PEDS0005_T1_doxorubicin,
               annotated_final$HepG2_doxorubicin_clone2,
               annotated_final$MCF10A_doxorubicin_clone1,
               annotated_final$MCF10A_doxorubicin_clone2)
doxo2 <- rbind(annotated_final$`CHLA-06-ATRT_doxorubicin`,
               annotated_final$PEDS9001_T1_doxorubicin,
               annotated_final$HepG2_doxorubicin_clone1)
sig_list <- list(doxo1, doxo2)
names(sig_list) <- c("SBS-Doxorubicin-1", "SBS-Doxorubicin-2")

# starting with coding:
  # missense_variant
  # stop_gained
  # synonymous_variant
muts_df <- c()
coding_cats_df <- c()

for (i in 1:length(sig_list)) {
  
  # subset for each df
  dat <- sig_list[[i]]
  
  # define how many coding variants 
  coding <- dat %>% filter(coding == "Yes")
  
  # calculate % of mutations that are coding and round
  coding_percent <- (nrow(coding)/nrow(dat)) * 100
  coding_percent <- signif(coding_percent, digits = 3)
  
  # append data to df
  muts_df <- rbind(muts_df, cbind(names(sig_list)[i], coding_percent))
  
  # count number of occurences of each mutation type for coding mutations
  counts <- coding %>% select(so) %>% count(so) %>% pivot_wider(names_from = so, values_from = n)
  
  # check which categories we have
  cats <- c("missense_variant", "stop_gained", "synonymous_variant")
  missing <- setdiff(cats, names(counts))
  counts[missing] <- 0
  counts <- counts[,cats]
  
  # want only columns that are one of 3: missense_variant, stop_gained, synonymous_variant
  counts <- counts[,c("missense_variant", "stop_gained", "synonymous_variant")]
  
  # add data to df
  coding_cats_df <- rbind(coding_cats_df, cbind(names(sig_list)[i], counts[1,]))
  
  rm(coding, dat, counts, coding_percent, cats, missing);gc()
  
}

rm(i);gc()

# rename columns
colnames(muts_df) <- c("sample", "percent_coding")
colnames(coding_cats_df)[1] <- "sample"

# transpose the df for plotting
coding_cats_df_transposed <- coding_cats_df |> t() |> as.data.frame()
colnames(coding_cats_df_transposed) <- coding_cats_df_transposed[1,]
coding_cats_df_transposed <- coding_cats_df_transposed[-1,]
coding_cats_df_transposed$so <- rownames(coding_cats_df_transposed)
rownames(coding_cats_df_transposed) <- NULL

coding_cats_df_transposed[,1:2] <- sapply(coding_cats_df_transposed[,1:2], as.numeric)
str(coding_cats_df_transposed)

# rename so column values for plotting
coding_cats_df_transposed$so <- c("Missense", "Nonsense", "Synonymous")

# plot piecharts
# SBS-Doxorubicin-1
df <- coding_cats_df_transposed[,c(1,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = so)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant type", values = c("Missense" = "#ff7249", 
                                                      "Nonsense" = "#6cab57", 
                                                      "Synonymous" = "#73c4f4")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)

# save plot
ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8B_1.png"), plot = p)

# SBS-Doxorubicin-2
df <- coding_cats_df_transposed[,c(2,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = so)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant type", values = c("Missense" = "#ff7249", 
                                                      "Nonsense" = "#6cab57", 
                                                      "Synonymous" = "#73c4f4")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)


ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8B_2.png"), plot = p)

# clean environment
rm(coding_cats_df, coding_cats_df_transposed, df, p, sample); gc()

# genic non-coding
  # intron_variant
  # 3_prime_UTR_variant
  # 2kb_upstream_variant (promoter)
  # 5_prime_UTR_variant
  # splice_site_variant

percent_genic_nc <- c()
genic_nc_df <- c()

for (i in 1:length(sig_list)) {
  
  # filter for each sample
  df <- sig_list[[i]]
  
  # define gene associated non-coding regions
  nc <- df %>% filter(!coding == "Yes") %>% filter(!so == "") %>% filter(!so == "2kb_downstream_variant")
  
  # % of mutations which are genic non-coding
  percent <- (nrow(nc)/nrow(df))*100
  
  # create row for df
  prow <- cbind(names(sig_list)[i], signif(percent, digits = 3))
  
  # append to df
  percent_genic_nc <- rbind(percent_genic_nc, prow)
  
  # count number of occurences of each mutation type for coding mutations
  counts <- nc %>% select(so) %>% count(so) %>% pivot_wider(names_from = so, values_from = n)
  
  # check which categories we have
  cats <- c("intron_variant", "3_prime_UTR_variant", "2kb_upstream_variant", "5_prime_UTR_variant", "splice_site_variant")
  missing <- setdiff(cats, names(counts))
  counts[missing] <- 0
  counts <- counts[,cats]
  
  # add data to df
  genic_nc_df <- rbind(genic_nc_df, cbind(names(sig_list)[i], counts[1,]))
  
  # clean environment
  rm(df, nc, percent, prow, counts, cats, missing); gc()
  
}

# clean up df by adding column names
colnames(genic_nc_df)[1] <- "sample"

# append percent_genic_nc to muts_df
muts_df <- cbind(muts_df, percent_genic_nc[,2])
colnames(muts_df)[3] <- "percent_genic_non-coding"

rm(percent_genic_nc); gc()

# transpose the df for plotting
genic_nc_df_transposed <- genic_nc_df |> t() |> as.data.frame()
colnames(genic_nc_df_transposed) <- genic_nc_df_transposed[1,]
genic_nc_df_transposed <- genic_nc_df_transposed[-1,]
genic_nc_df_transposed$so <- rownames(genic_nc_df_transposed)
rownames(genic_nc_df_transposed) <- NULL

str(genic_nc_df_transposed)
genic_nc_df_transposed[,1:2] <- sapply(genic_nc_df_transposed[,1:2], as.numeric)
str(genic_nc_df_transposed)

# rename so column values for plotting
genic_nc_df_transposed$so <- c("Intron", "3'UTR", "Promoter", "5'UTR", "Splice site")

# plot piecharts
# SBS-Doxorubicin-1
df <- genic_nc_df_transposed[,c(1,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = so)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant type", values = c("Intron" = "#fc5e69", 
                                                      "3'UTR" = "#4480f0", 
                                                      "Promoter" = "#ffd700",
                                                      "5'UTR" = "#00a050",
                                                      "Splice site" = "#c2beff")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)

# save
ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8C_1.png"), plot = p)

# SBS-Doxorubicin-2
df <- genic_nc_df_transposed[,c(2,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = so)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant type", values = c("Intron" = "#fc5e69", 
                                                      "3'UTR" = "#4480f0", 
                                                      "Promoter" = "#ffd700",
                                                      "5'UTR" = "#00a050",
                                                      "Splice site" = "#c2beff")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)

# save
ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8C_2.png"), plot = p)

# clean environment
rm(df, genic_nc_df, genic_nc_df_transposed, i, p, sample); gc()

# intergenic
  # no sequence ontology
  # 2kb downstream

intergenic_percent <- c()

for (i in 1:length(sig_list)) {
  
  # subset df
  df <- sig_list[[i]]
  
  intergenic <- rbind((df %>% filter(so == "")), ((df %>% filter(so == "2kb_downstream_variant"))))
  
  int_percent <- (nrow(intergenic)/nrow(df))*100
  
  prow <- cbind(names(sig_list)[i], signif(int_percent, digits = 3))
  
  intergenic_percent <- rbind(intergenic_percent, prow)
}

# append to muts df
muts_df <- cbind(muts_df, intergenic_percent[,2])
colnames(muts_df)[4] <- "intergenic_percent"

# clean environment
rm(df, intergenic, intergenic_percent, prow, i, int_percent); gc()

# transpose df
percent_df <- muts_df
percent_df <- percent_df |> t() |> as.data.frame()
colnames(percent_df) <- percent_df[1,]
percent_df <- percent_df[-1,]
percent_df$type <- c("Coding", "Gene-associated non-coding", "Intergenic")
rownames(percent_df) <- NULL

# ensure the numbers are numeric
str(percent_df)
percent_df[,1:2] <- sapply(percent_df[,1:2], as.numeric)
str(percent_df)

# plot
# SBS-Doxorubicin-1
df <- percent_df[,c(1,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = type)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant location by region type", values = c("Coding" = "#c386f1", 
                                                                         "Gene-associated non-coding" = "#cea340", 
                                                                         "Intergenic" = "gray")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)

# save
ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8A_1.png"), plot = p, height = 5, width = 7)

# SBS-Doxorubicin-2
df <- percent_df[,c(2,3)]
sample <- colnames(df)[1]
colnames(df)[1] <- "sample"

p <- ggplot(df, aes(x = "", y = sample, fill = type)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle(sample) +
  scale_fill_manual(name = "Variant location by region type", values = c("Coding" = "#c386f1", 
                                                                         "Gene-associated non-coding" = "#cea340", 
                                                                         "Intergenic" = "gray")) +
  theme(plot.title = element_text(hjust = 0.5, vjust = -5, face = "bold", size = 16))
print(p)

# save
ggsave(paste0("~/doxorubicin_mutSig/figures/FigS8/Figure_S8A_2.png"), plot = p, height = 5, width = 7)

# clean environment
rm(list = ls()); gc()