# Skinner, KT., et al, 2026. "Derivation of a doxorubicin mutational signature in cancer". Genome Research
# Contact for questions: Katie Skinner; katie.skinner@emory.edu

# Code for Table S8 of manuscript

# load libraries
library(sigProcessor)
library(tidyverse)
library(data.table)

# set working directory
setwd("~/doxorubicin_mutSig/data/")

# read in table of annotated mutations
# this file was generated by inputting VCFs for each doxorubicin exposed sample into OpenCRAVAT
annotated <- rbind(read.table("/path/to/BT16_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/CHLA-06-ATRT_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/PEDS0005_T1_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/PEDS9001_T1_doxorubicin_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/HepG2_doxorubicin_clone1_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/HepG2_doxorubicin_clone2_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/MCF10A_doxorubicin_clone1_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T),
                   read.table("/path/to/MCF10A_doxorubicin_clone2_annotated_VCF", header = T, sep = "\t", comment.char = "#", quote = "", fill = T)) # data not included due to controlled access

# read in and process SBS VCFs
genome_data <- prepare_sbs96_vcf(c("/path/to/BT16_doxorubicin_SBS_VCF",
                                   "/path/to/CHLA-06-ATRT_doxorubicin_SBS_VCF",
                                   "/path/to/PEDS0005_T1_doxorubicin_SBS_VCF",
                                   "/path/to/PEDS9001_T1_doxorubicin_SBS_VCF",
                                   "/path/to/HepG2_doxorubicin_clone1_SBS_VCF",
                                   "/path/to/HepG2_doxorubicin_clone2_SBS_VCF",
                                   "/path/to/MCF10A_doxorubicin_clone1_SBS_VCF",
                                   "/path/to/MCF10A_doxorubicin_clone2_SBS_VCF")) # data not included due to controlled access

# loop through both lists and confirm that they are in the same order
for (i in 1:length(annotated)) {
  
  cat(paste0("Sample index: ", i, ". "))
  cat(paste0("Annotated sample: ", annotated[[i]]$samples |> unique(), ". "))
  cat(paste0("Genome sample: ", genome_data[[i]]$sample |> unique(), ". "))
  cat("\n")
  
}

# both dfs are in the same order!

# process the dfs
annotated_subset <- list()
for (i in 1:length(annotated)) {
  
  # subset each list for each sample
  a <- annotated[[i]]
  g <- genome_data[[i]]
  
  # narrow down the columns
  a <- a %>% dplyr::select(chrom, pos, ref_base, alt_base, exonno, coding, hugo, so, samples, transcript)
  g <- g %>% select(chrom, pos, sbs6, sample, strand)
  
  # filter to remove non-canonical chromosomes in annotated df
  a <- a %>% filter(chrom %in% paste0("chr", c(1:22, "X", "Y", "M")))
  
  # ensure the chromosome names are in the same format
  a$chrom <- str_replace(a$chrom, pattern = "chrM", replacement = "chrMT")
  
  # in genome data, add a ref and alt base 
  g <- g %>% mutate(ref = substr(g$sbs6, 1, 1),
                    alt = substr(g$sbs6, 3, 3))
  
  # convert everything back to a mix of purines and pyrimidines
  # strand of -1 indicates that the reference base was a purine, thus both ref>alt were converted to their complement
  ref_base <- c()
  alt_base <- c()
  
  for (j in 1:nrow(g)) {
    
    if(g$strand[j] == -1) {
      
      ref_base <- c(ref_base, chartr(old="ATGC", new="TACG", g$ref[j]))
      alt_base <- c(alt_base, chartr(old="ATGC", new="TACG", g$alt[j]))
      
    } else {
      
      ref_base <- c(ref_base, g$ref[j])
      alt_base <- c(alt_base, g$alt[j])
      
    }
  }
  
  # add these to the df
  g$ref_base <- ref_base
  g$alt_base <- alt_base
  
  rm(ref_base, alt_base, j); gc() # clean
  
  # remove INDELs from annotated list
  a <- a %>% filter(!ref_base == "-" & !alt_base == "-") %>%
    filter(nchar(ref_base) == nchar((alt_base)))
  
  # SigProfiler treats dinucleotide substitutions as two single base substitutions
  # find the DBSs
  dbs <- a %>% filter(nchar(ref_base) == 2 & nchar(alt_base) == 2)
  
  # split up each DBS
  dbs_split <- c()
  for (x in 1:nrow(dbs)) {
    
    # define ref bases
    ref1 <- substr(dbs$ref_base[x], 1, 1)
    ref2 <- substr(dbs$ref_base[x], 2, 2)
    
    # define alt bases
    alt1 <- substr(dbs$alt_base[x], 1, 1)
    alt2 <- substr(dbs$alt_base[x], 2, 2)
    
    # build the row
    r1 <- c(dbs$chrom[x], dbs$pos[x], ref1, alt1, dbs$exonno[x], dbs$coding[x], dbs$hugo[x], "DBS", dbs$samples[x], dbs$transcript[x])
    r2 <- c(dbs$chrom[x], dbs$pos[x]+1, ref2, alt2, dbs$exonno[x], dbs$coding[x], dbs$hugo[x], "DBS", dbs$samples[x], dbs$transcript[x])
    
    # append the row to the df
    dbs_split <- rbind(dbs_split, r1, r2)
    
  }
  
  rm(ref1, ref2, alt1, alt2, r1, r2, dbs); gc() # clean
  
  # convert to df
  dbs_split <- dbs_split |> as.data.frame()
  
  # add column names
  colnames(dbs_split) <- colnames(a)
  
  # append to the annotated df
  a <- rbind(a, dbs_split)
  
  # reset rownames
  rownames(a) <- NULL
  
  # create an ID for chrom, pos, ref, and alt to facilitate filtering
  a$ID <- paste0(a$chrom, "_", a$pos, "_", a$ref_base, "/", a$alt_base)
  g$ID <- paste0(g$chrom, "_", g$pos, "_", g$ref_base, "/", g$alt_base)
  
  # find the overlap
  s <- a %>% filter(ID %in% g$ID)
  
  # add to list
  annotated_subset[[i]] <- s
  names(annotated_subset)[i] <- g$sample |> unique()
  
  # clean environment
  rm(a, dbs_split, g, s, x); gc()
  
}

# now that we have our dfs, loop through and determine if any DBS fell in coding regions
annotated_final <- list()
for (i in 1:length(annotated_subset)) {
  
  # subset list
  df <- annotated_subset[[i]]
  
  # locate our DBSs, encoded as "DBS" in the "so" column
  # also check if any of these are coding
  dbs <- df %>% filter(so == "DBS" & coding == "Yes")
  
  # print message
  message(paste0("Number of coding DBSs in ", names(annotated_subset)[i], ": ", nrow(dbs)))
  
  # remove "DBS" label from "so" column
  if (nrow(dbs) == 0) {
    
    df$so <- str_remove(df$so, "DBS")
    
  } else {
    
    df$so <- str_remove(df$so, "DBS")
    
    # also print off the sample and coordinates for the coding DBSs
    cat(paste0("Sample: ", names(annotated_subset)[i], "\n"))
    cat(paste0("Coordinates of coding DBSs:\n"))
    print(dbs)
    
  }
  
  # append the scrubbed df to final list
  annotated_final[[i]] <- df
  names(annotated_final)[i] <- names(annotated_subset)[i]
  
  # clean environment
  rm(dbs, df); gc()
  
}

# according to the output of the above loop, we have 2 coding DBSs in CHLA-06-ATRT_doxorubicin
# does splitting this DBS up still result in a coding change? 
  # yes. go into IGV to validate if both are still missense
  # yes they are.

# update each entry to reflect that
# index of each mutation: 
  # 9179
  # 9180

# fix
annotated_final$`CHLA-06-ATRT_doxorubicin`[9179,8] <- "missense"
annotated_final$`CHLA-06-ATRT_doxorubicin`[9180,8] <- "missense"

# sanity check
annotated_final$`CHLA-06-ATRT_doxorubicin`[9179,]
annotated_final$`CHLA-06-ATRT_doxorubicin`[9180,] # both look good!

# clean environment
rm(annotated, annotated_subset, genome_data, i); gc()

# next, we want to characterise the coding mutations

# starting with coding:
  # missense_variant
  # stop_gained
  # synonymous_variant
coding_cats_df <- c()

for (i in 1:length(annotated_final)) {
  
  # subset for each df
  dat <- annotated_final[[i]]
  
  # define how many coding variants 
  coding <- dat %>% filter(coding == "Yes")
  
  # count number of occurences of each mutation type for coding mutations
  counts <- coding %>% select(so) %>% count(so) %>% pivot_wider(names_from = so, values_from = n)
  
  # check which categories we have
  cats <- c("missense_variant", "stop_gained", "synonymous_variant")
  missing <- setdiff(cats, names(counts))
  counts[missing] <- 0
  counts <- counts[,cats]
  
  # want only columns that are one of 3: missense_variant, stop_gained, synonymous_variant
  counts <- counts[,c("missense_variant", "stop_gained", "synonymous_variant")]
  
  # add data to df
  coding_cats_df <- rbind(coding_cats_df, cbind(names(annotated_final)[i], counts[1,]))
  
  rm(coding, dat, counts, cats, missing);gc()
  
}

rm(i);gc()

# rename columns
colnames(coding_cats_df) <- c("Sample", "Number of missense variants", "Number of nonsense variants", "Number of synonymous variants")

# reshuffle sample order
coding_final <- coding_cats_df[c(1,3,6:8,2,4,5),]

# save
write_tsv(x = coding_final, file = "./tables/TableS8.tsv")

# clean environment
rm(annotated_final, coding_cats_df, coding_final); gc()
